name: Deploy MultiDocker
on:
  push:
    branches:
      - main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - run: docker build -t manvendra1097/multi-client-10-14 ./client
        - run: docker build -t manvendra1097/multi-nginx-10-14 ./nginx
        - run: docker build -t manvendra1097/multi-server-10-14 ./server
        - run: docker build -t manvendra1097/multi-worker-10-14 ./worker

    push:
      steps:
        - run: docker push cygnetops/multi-client-10-14
        - run: docker push cygnetops/multi-nginx-10-14
        - run: docker push cygnetops/multi-server-10-14
        - run: docker push cygnetops/multi-worker-10-14
